### ISSUE TITLE
Zooming on MacOS causes scrolling

### ISSUE THREAD

**Issue by Keynub** [LinkedFluuuush/RPG-Sheet#1]
Version : MacOS 0.3.0

Issue : When using Cmd+Mousewheel to zoom in or out on MacOS Catalina, the default behavior of the mousewheel also applies : the page scrolls.

Expected : The page should not scroll when zooming.

**Comment by LinkedFluuuush** [comment]
Issue fixed in Hotfix 0.3.1
Thank you for reporting it !
